version: '3.9'

services:
  deno:
    container_name: deno_app
    working_dir: /app
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    env_file:
      - ./.env